Import Pandas

In [33]:
import pandas as pd

LOAD DATA

In [34]:
df_wisata = pd.read_csv("../data/processed/wisata_final.csv")
df_kuliner = pd.read_csv("../data/processed/kuliner_final.csv")
df_hotel = pd.read_csv("../data/processed/hotel_final.csv")

print("Kolom wisata:", df_wisata.columns)

Kolom wisata: Index(['query', 'name', 'name_for_emails', 'subtypes', 'category', 'type',
       'phone', 'website', 'address', 'street', 'city', 'county', 'state',
       'state_code', 'postal_code', 'country', 'country_code', 'latitude',
       'longitude', 'h3', 'time_zone', 'plus_code', 'area_service', 'rating',
       'reviews', 'reviews_link', 'reviews_tags', 'reviews_per_score',
       'reviews_per_score_1', 'reviews_per_score_2', 'reviews_per_score_3',
       'reviews_per_score_4', 'reviews_per_score_5', 'photos_count', 'photo',
       'street_view', 'logo', 'located_in', 'located_google_id',
       'business_status', 'working_hours', 'working_hours_csv_compatible',
       'other_hours', 'popular_times', 'typical_time_spent', 'range', 'prices',
       'reservation_links', 'booking_appointment_link', 'menu_link',
       'order_links', 'about', 'description', 'posts', 'verified', 'owner_id',
       'owner_title', 'owner_link', 'location_link', 'location_reviews_link',
       'place_id', 'google_id', 'cid', 'kgmid', 'reviews_id'],
      dtype='str')

CEK KOLOM

In [35]:
print("Wisata:", df_wisata.columns)
print("Kuliner:", df_kuliner.columns)
print("Hotel:", df_hotel.columns)

Wisata: Index(['query', 'name', 'name_for_emails', 'subtypes', 'category', 'type',
       'phone', 'website', 'address', 'street', 'city', 'county', 'state',
       'state_code', 'postal_code', 'country', 'country_code', 'latitude',
       'longitude', 'h3', 'time_zone', 'plus_code', 'area_service', 'rating',
       'reviews', 'reviews_link', 'reviews_tags', 'reviews_per_score',
       'reviews_per_score_1', 'reviews_per_score_2', 'reviews_per_score_3',
       'reviews_per_score_4', 'reviews_per_score_5', 'photos_count', 'photo',
       'street_view', 'logo', 'located_in', 'located_google_id',
       'business_status', 'working_hours', 'working_hours_csv_compatible',
       'other_hours', 'popular_times', 'typical_time_spent', 'range', 'prices',
       'reservation_links', 'booking_appointment_link', 'menu_link',
       'order_links', 'about', 'description', 'posts', 'verified', 'owner_id',
       'owner_title', 'owner_link', 'location_link', 'location_reviews_link',
       'place_id', 'google_id', 'cid', 'kgmid', 'reviews_id'],
      dtype='str')
Kuliner: Index(['query', 'name', 'name_for_emails', 'subtypes', 'category', 'type',
       'phone', 'website', 'address', 'street', 'city', 'county', 'state',
       'state_code', 'postal_code', 'country', 'country_code', 'latitude',
       'longitude', 'h3', 'time_zone', 'plus_code', 'area_service', 'rating',
       'reviews', 'reviews_link', 'reviews_tags', 'reviews_per_score',
       'reviews_per_score_1', 'reviews_per_score_2', 'reviews_per_score_3',
       'reviews_per_score_4', 'reviews_per_score_5', 'photos_count', 'photo',
       'street_view', 'logo', 'located_in', 'located_google_id',
       'business_status', 'working_hours', 'working_hours_csv_compatible',
       'other_hours', 'popular_times', 'typical_time_spent', 'range', 'prices',
       'reservation_links', 'booking_appointment_link', 'menu_link',
       'order_links', 'about', 'description', 'posts', 'verified', 'owner_id',
       'owner_title', 'owner_link', 'location_link', 'location_reviews_link',
       'place_id', 'google_id', 'cid', 'kgmid', 'reviews_id'],
      dtype='str')
Hotel: Index(['query', 'name', 'name_for_emails', 'subtypes', 'category', 'type',
       'phone', 'website', 'address', 'street', 'city', 'county', 'state',
       'state_code', 'postal_code', 'country', 'country_code', 'latitude',
       'longitude', 'h3', 'time_zone', 'plus_code', 'area_service', 'rating',
       'reviews', 'reviews_link', 'reviews_tags', 'reviews_per_score',
       'reviews_per_score_1', 'reviews_per_score_2', 'reviews_per_score_3',
       'reviews_per_score_4', 'reviews_per_score_5', 'photos_count', 'photo',
       'street_view', 'logo', 'located_in', 'located_google_id',
       'business_status', 'working_hours', 'working_hours_csv_compatible',
       'other_hours', 'popular_times', 'typical_time_spent', 'range', 'prices',
       'reservation_links', 'booking_appointment_link', 'menu_link',
       'order_links', 'about', 'description', 'posts', 'verified', 'owner_id',
       'owner_title', 'owner_link', 'location_link', 'location_reviews_link',
       'place_id', 'google_id', 'cid', 'kgmid', 'reviews_id'],
      dtype='str')

NORMALISASI NAMA KOLOM

In [36]:
df_wisata.columns = df_wisata.columns.str.lower()
df_kuliner.columns = df_kuliner.columns.str.lower()
df_hotel.columns = df_hotel.columns.str.lower()

SAMAIN NAMA KOLOM (JIKA BERBEDA)

In [37]:
print(df_wisata.columns)
print(df_kuliner.columns)
print(df_hotel.columns)

Index(['query', 'name', 'name_for_emails', 'subtypes', 'category', 'type',
       'phone', 'website', 'address', 'street', 'city', 'county', 'state',
       'state_code', 'postal_code', 'country', 'country_code', 'latitude',
       'longitude', 'h3', 'time_zone', 'plus_code', 'area_service', 'rating',
       'reviews', 'reviews_link', 'reviews_tags', 'reviews_per_score',
       'reviews_per_score_1', 'reviews_per_score_2', 'reviews_per_score_3',
       'reviews_per_score_4', 'reviews_per_score_5', 'photos_count', 'photo',
       'street_view', 'logo', 'located_in', 'located_google_id',
       'business_status', 'working_hours', 'working_hours_csv_compatible',
       'other_hours', 'popular_times', 'typical_time_spent', 'range', 'prices',
       'reservation_links', 'booking_appointment_link', 'menu_link',
       'order_links', 'about', 'description', 'posts', 'verified', 'owner_id',
       'owner_title', 'owner_link', 'location_link', 'location_reviews_link',
       'place_id', 'google_id', 'cid', 'kgmid', 'reviews_id'],
      dtype='str')
Index(['query', 'name', 'name_for_emails', 'subtypes', 'category', 'type',
       'phone', 'website', 'address', 'street', 'city', 'county', 'state',
       'state_code', 'postal_code', 'country', 'country_code', 'latitude',
       'longitude', 'h3', 'time_zone', 'plus_code', 'area_service', 'rating',
       'reviews', 'reviews_link', 'reviews_tags', 'reviews_per_score',
       'reviews_per_score_1', 'reviews_per_score_2', 'reviews_per_score_3',
       'reviews_per_score_4', 'reviews_per_score_5', 'photos_count', 'photo',
       'street_view', 'logo', 'located_in', 'located_google_id',
       'business_status', 'working_hours', 'working_hours_csv_compatible',
       'other_hours', 'popular_times', 'typical_time_spent', 'range', 'prices',
       'reservation_links', 'booking_appointment_link', 'menu_link',
       'order_links', 'about', 'description', 'posts', 'verified', 'owner_id',
       'owner_title', 'owner_link', 'location_link', 'location_reviews_link',
       'place_id', 'google_id', 'cid', 'kgmid', 'reviews_id'],
      dtype='str')
Index(['query', 'name', 'name_for_emails', 'subtypes', 'category', 'type',
       'phone', 'website', 'address', 'street', 'city', 'county', 'state',
       'state_code', 'postal_code', 'country', 'country_code', 'latitude',
       'longitude', 'h3', 'time_zone', 'plus_code', 'area_service', 'rating',
       'reviews', 'reviews_link', 'reviews_tags', 'reviews_per_score',
       'reviews_per_score_1', 'reviews_per_score_2', 'reviews_per_score_3',
       'reviews_per_score_4', 'reviews_per_score_5', 'photos_count', 'photo',
       'street_view', 'logo', 'located_in', 'located_google_id',
       'business_status', 'working_hours', 'working_hours_csv_compatible',
       'other_hours', 'popular_times', 'typical_time_spent', 'range', 'prices',
       'reservation_links', 'booking_appointment_link', 'menu_link',
       'order_links', 'about', 'description', 'posts', 'verified', 'owner_id',
       'owner_title', 'owner_link', 'location_link', 'location_reviews_link',
       'place_id', 'google_id', 'cid', 'kgmid', 'reviews_id'],
      dtype='str')

PILIH KOLOM PENTING

In [38]:
cols = ["name", "category", "rating", "address", "subtypes"]

df_wisata = df_wisata[cols]
df_kuliner = df_kuliner[cols]
df_hotel = df_hotel[cols]

print("Kolom sudah disederhanakan")

Kolom sudah disederhanakan

tambah type

In [39]:
df_wisata["type"] = "wisata"
df_kuliner["type"] = "kuliner"
df_hotel["type"] = "hotel"

print("Type berhasil ditambahkan")

Type berhasil ditambahkan

HAPUS DATA KOSONG

In [40]:
# HAPUS DATA KOSONG - ONLY CRITICAL COLUMNS
# Only drop if name or category is missing (these are essential)
df_wisata = df_wisata.dropna(subset=["name", "category"])
df_kuliner = df_kuliner.dropna(subset=["name", "category"])
df_hotel = df_hotel.dropna(subset=["name", "category"])

# Fill missing subtypes with empty string (it's optional)
df_wisata["subtypes"] = df_wisata["subtypes"].fillna("")
df_kuliner["subtypes"] = df_kuliner["subtypes"].fillna("")
df_hotel["subtypes"] = df_hotel["subtypes"].fillna("")

print("Data kosong sudah dihapus (hanya critical columns)")

Data kosong sudah dihapus (hanya critical columns)

NORMALISASI TEKS

In [41]:
df_wisata["category"] = df_wisata["category"].str.lower()
df_kuliner["category"] = df_kuliner["category"].str.lower()
df_hotel["category"] = df_hotel["category"].str.lower()

print("Category sudah dinormalisasi")

Category sudah dinormalisasi

Hapus beberapa yang duplikat

In [42]:
# Hapus beberapa yang duplikat - gunakan name + address untuk uniqueness
# Ini menangani kasus: "Warung X" di lokasi berbeda adalah tempat berbeda
df_wisata = df_wisata.drop_duplicates(subset=["name", "address"])
df_kuliner = df_kuliner.drop_duplicates(subset=["name", "address"])
df_hotel = df_hotel.drop_duplicates(subset=["name", "address"])

print("Duplikat dihapus (berdasarkan name + address)")

Duplikat dihapus (berdasarkan name + address)

MERGE ALL

In [43]:
df_all = pd.concat([df_wisata, df_kuliner, df_hotel], ignore_index=True)

print("Total data gabungan:", len(df_all))
df_all.head()

Total data gabungan: 730

,name,category,rating,address,subtypes,type
0,Taman Budaya Yogyakarta,pusat kebudayaan,4.6,"Jl. Sriwedani No.1, Ngupasan, Kec. Gondomanan,...","Cultural center, Concert hall, Event venue",wisata
1,Vredeburg Fort Museum,museums,4.7,"Jl. Margo Mulyo No.6, Ngupasan, Kec. Gondomana...","Tourist attraction, Fortress, Natural history ...",wisata
2,Situs Pesanggrahan Rejawinangun,attractions,4.4,"Jl. Veteran No.77, Warungboto, Kec. Umbulharjo...","Tourist attraction, Historical landmark",wisata
3,Taman Sari Tourist Village,attractions,4.6,"Patehan, Kraton, Yogyakarta City, Special Regi...","Tourist attraction, Historical landmark",wisata
4,Bentara Budaya Yogyakarta (BBY),attractions,4.6,"Jl. Suroto No.2, Kotabaru, Kec. Gondokusuman, ...","Tourist attraction, Art center",wisata

In [44]:
df_all.to_csv("../data/processed/merged_dataset.csv", index=False)

print("Dataset siap ML ")

Dataset siap ML

In [45]:
df_all.columns

Index(['name', 'category', 'rating', 'address', 'subtypes', 'type'], dtype='str')

In [46]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      730 non-null    str
 1   category  730 non-null    str
 2   rating    726 non-null    float64
 3   address   730 non-null    str
 4   subtypes  730 non-null    str
 5   type      730 non-null    str
dtypes: float64(1), str(5)
memory usage: 34.3 KB

In [47]:
df_all["type"].value_counts()

type
kuliner    262
hotel      250
wisata     218
Name: count, dtype: int64

In [48]:
df_all.sample(10)

,name,category,rating,address,subtypes,type
40,Dawangsari Temple,attractions,4.5,"6FGX+926 Dawang Sari, Dowang Sari, Sambirejo, ...","Buddhist temple, Tourist attraction",wisata
43,ꦱꦁꦒꦂꦕꦤ꧀ꦝꦶꦱꦥ꧀ꦠꦉꦁꦒꦪꦺꦴꦒꦾꦏꦂꦠ (Sanggar Candi Sapta ...,place of worship,4.7,"59VG+QFR, Wirogunan, Mergangsan, Yogyakarta Ci...",Place of worship,wisata
514,Hotel O Jalan Malioboro Near Stasiun Tugu Yogy...,hotels,3.8,"Jl. Gowongan Kidul No.19, Gowongan, Kec. Jetis...",Hotel,hotel
487,The Victoria Hotel Yogyakarta,hotels,4.4,"Jl. Pakel No.5, Tempel, Caturtunggal, Kec. Dep...",Hotel,hotel
694,Hotel Maerakatja Jogjakarta,hotels,4.2,"Jl. R.W. Monginsidi No.22B, Karangwaru, Kec. T...",Hotel,hotel
145,Toko Gunung Mas,toko jam,4.5,"Jl. Jend. Ahmad Yani No.37, Ngupasan, Kec. Gon...",Watch store,wisata
425,Rumah Makan Padang Murah,restoran padang,4.4,"694F+P8W, Jl. Hayam Wuruk, Bausasran, Kec. Dan...","Padang restaurant, Buffet restaurant, Diner",kuliner
130,Ancient Volcano Nglanggeran,attractions,4.6,"Nglanggeran Wetan, Nglanggeran, Patuk, Gunungk...",Tourist attraction,wisata
356,Angkringan Jogja,coffee shops,5.0,"Jl. Pangurakan No.Km 0, Prawirodirjan, Kec. Go...",Coffee shop,kuliner
468,Rumah Makan Bahagia,restoran padang,5.0,"Jl. Margo Mulyo No.6, Ngupasan, Kec. Gondomana...","Padang restaurant, Indonesian restaurant",kuliner