In [3]:
import pandas as pd

df = pd.read_csv("../data/processed/tfidf_dataset.csv")

df.tail()

,name,category,rating,address,subtypes,type,price_estimate,subtypes_clean,text
740,Villa Kamar Tamu Umbulharjo,villa,5.0,"Jl. Umbul Tirtho, Warungboto, Kec. Umbulharjo,...",Villa,hotel,300000,villa,villa kamar tamu umbulharjo villa hotel lodgin...
741,Arah Living,hotels,4.8,"Gg. Jemb. Merah No.104C, Soropadan, Condongcat...",Hotel,hotel,300000,hotel,arah living hotel hotel lodging penginapan
742,Anjuma Backpacker,hostel,4.9,"Jl. Tegal Lempuyangan No.23, Bausasran, Kec. D...",Hostel,hotel,300000,hostel,anjuma backpacker hostel hotel lodging penginapan
743,Aliya Homestay,pondok,4.3,"Jl. Jagung No.21, Semaki, Kec. Umbulharjo, Kot...",Lodge,hotel,300000,lodge,aliya homestay lodge hotel lodging penginapan
744,Urbanview Hotel Tan Jokteng Prawirotaman,hotels,4.1,"Jl. Mangkuyudan No.47, Mantrijeron, Kec. Mantr...",Hotel,hotel,300000,hotel,urbanview hotel tan jokteng prawirotaman hotel...

In [4]:
df[["name", "type", "price_estimate"]]

                                         name    type  price_estimate
0                     Taman Budaya Yogyakarta  wisata           25000
1                       Vredeburg Fort Museum  wisata           25000
2             Situs Pesanggrahan Rejawinangun  wisata           25000
3                  Taman Sari Tourist Village  wisata           25000
4             Bentara Budaya Yogyakarta (BBY)  wisata           25000
..                                        ...     ...             ...
740               Villa Kamar Tamu Umbulharjo   hotel          300000
741                               Arah Living   hotel          300000
742                         Anjuma Backpacker   hotel          300000
743                            Aliya Homestay   hotel          300000
744  Urbanview Hotel Tan Jokteng Prawirotaman   hotel          300000

[745 rows x 3 columns]